name: wallet_dart
description: Candide helper/essential shared functions.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^2.7.1
  eth_sig_util: ^0.0.9
  http: ^1.1.0
  steel_crypt: ^3.0.0+1
  pointycastle: ^3.6.2
  bip39: ^1.0.6
  flutter_bitcoin: ^1.0.1

dev_dependencies:
  web3dart_builders: ^0.0.7
  build_runner: ^2.0.3
  test: ^1.21.0