name: wallet_dart
description: Candide helper/essential shared functions.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  eth_sig_util: ^0.0.9
  http: ^1.1.0
  steel_crypt: ^3.0.0+1
  pointycastle: ^3.6.2
  bip39: ^1.0.6
  flutter_bitcoin: ^1.0.1
  web3dart:
    git:
      url: https://github.com/tct68/web3dart.git

dev_dependencies:
  build_runner: ^2.0.3
  test: ^1.21.0
  web3dart_builders:
    git:
      url: https://github.com/tct68/web3dart_builders.git